name: Escaneo Nmap

on:
  push:
    paths:
      - "targets.txt"

jobs:
  nmap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Nmap
        run: |
          sudo apt-get update
          sudo apt-get install -y nmap

      - name: Ejecutar escaneo
        run: |
          mkdir -p evidencias
          nmap -F scanme.nmap.org -oN evidencias/resultados-nmap.txt

      - name: Mostrar resultados
        run: |
          cat evidencias/resultados-nmap.txt

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Guardar evidencias
        run: |
          git add evidencias/resultados-nmap.txt
          git commit -m "Actualizar resultados Nmap" || echo "Sin cambios"

      - name: Subir cambios
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Escaneo finalizado
        run: echo "Escaneo terminado correctamente"
